name: Publish to RStudio Connect
description: Publish to RStudio Connect via the rsconnect CLI
author: RStudio Developers
inputs:
  api-key:
    description: API key generated in RStudio Connect
  dir:
    description: Directory or directories containing the content to publish
    default: .
  url:
    description: RStudio Connect URL
runs:
  using: node12
  main: dist/index.js
