name: main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  main:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            action: setup-connect
            regress-with:
              api-key: bogus
              url: https://connect.example.org
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: yarn install
        working-directory: ${{ matrix.config.action }}
      - run: yarn build
        working-directory: ${{ matrix.config.action }}
      - run: yarn test
        working-directory: ${{ matrix.config.action }}
      - uses: ./${{ matrix.config.action }}
        with: ${{ matrix.config.regress-with }}
