name: main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  setup-connect:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    defaults:
      run:
        working-directory: setup-connect
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run: git diff --exit-code --ignore-all-space
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: ./setup-connect
        with:
          python: true
          r: false
      - run: rsconnect version
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 3.6.3
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libcurl4-openssl-dev
      - uses: ./setup-connect
        with:
          python: false
          r: true
      - run: Rscript --vanilla -e "packageVersion('rsconnect')"
  connect-publish:
    runs-on: ${{ matrix.os }}
    env:
      RSC_LICENSE: ${{ secrets.RSC_LICENSE }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    defaults:
      run:
        working-directory: connect-publish
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run: docker-compose up -d
      - run: |
          curl -o wait-for -fsSL https://raw.githubusercontent.com/eficode/wait-for/master/wait-for && \
          chmod +x wait-for
      - run: sha1sum __tests__/rstudio-connect.test.gcfg
      - run: docker-compose exec connect sha1sum /etc/rstudio-connect/rstudio-connect.gcfg
      - run: |
          ./wait-for 127.0.0.1:23939 -- \
            curl -L -vvv -H 'Authorization: Key ${{ secrets.RSTUDIO_CONNECT_API_KEY }}' \
              http://127.0.0.1:23939/__api__/server_settings
      - uses: ./connect-publish
        with:
          url: http://${{ secrets.RSTUDIO_CONNECT_API_KEY }}@127.0.0.1:23939
          dir: |
            ./connect-publish/__tests__/apps/plumber
            ./connect-publish/__tests__/apps/flask
      - if: failure()
        run: docker-compose logs
      - if: always()
        run: docker-compose down --remove-orphans
