name: Setup RStudio Connect environment
description: Setup an environment to work with an RStudio Connect API
author: RStudio Developers
inputs:
  rsconnect-python-version:
    description: Version of rsconnect-python to install
    default: latest
runs:
  using: node12
  main: dist/index.js
